import { posix } from "node:path";

export const DOCUMENTATION_STATUSES = [
  "draft",
  "specced",
  "active",
  "implemented",
  "superseded",
  "historical",
  "generated"
] as const;

export const DOCUMENTATION_EVIDENCE = [
  "not-run",
  "partial",
  "verified",
  "manual-gate-open"
] as const;

export const DOCUMENTATION_CONTRACTS = ["living", "closed"] as const;

export type DocumentationStatus = (typeof DOCUMENTATION_STATUSES)[number];
export type DocumentationEvidence = (typeof DOCUMENTATION_EVIDENCE)[number];
export type DocumentationContract = (typeof DOCUMENTATION_CONTRACTS)[number];

export interface DocumentationMetadata {
  readonly status: DocumentationStatus;
  readonly date: string;
  readonly owner: string;
  readonly lastVerified?: string;
  readonly evidence?: DocumentationEvidence;
  readonly parentGoal?: string;
  readonly supersededBy?: string;
  readonly contract?: DocumentationContract;
  readonly generatedBy?: string;
}

export interface DocumentationDiagnostic {
  readonly file: string;
  readonly line: number;
  readonly code: string;
  readonly message: string;
}

export interface DocumentationCheckInput {
  readonly files: Readonly<Record<string, string>>;
  readonly packageScripts: ReadonlySet<string>;
  readonly rootDocument?: string;
}

export interface DocumentationCheckResult {
  readonly diagnostics: readonly DocumentationDiagnostic[];
  readonly metadata: ReadonlyMap<string, DocumentationMetadata>;
  readonly reachability: ReadonlyMap<string, number>;
}

export interface SpecificationCatalogPlanEntry {
  readonly file: string;
  readonly group: string;
  readonly label: string;
  readonly status: DocumentationStatus;
  readonly contract: DocumentationContract;
  readonly owner: string;
  readonly date: string;
  readonly line: string;
}

const METADATA_FIELDS = new Map([
  ["Status", "status"],
  ["Date", "date"],
  ["Owner", "owner"],
  ["Last verified", "lastVerified"],
  ["Evidence", "evidence"],
  ["Parent goal", "parentGoal"],
  ["Superseded by", "supersededBy"],
  ["Contract", "contract"],
  ["Generated by", "generatedBy"]
] as const);

const REQUIRED_METADATA_FIELDS = ["status", "date", "owner"] as const;

const VOLATILE_FACT_FILES = new Set([
  "docs/operations/README.md",
  "docs/product/feature-inventory.md",
  "docs/project/backlog.md",
  "docs/technical/architecture.md",
  "docs/technical/testing.md",
  "docs/technical/testing/accessibility-manual.md",
  "docs/technical/testing/domain-and-integrations.md",
  "docs/technical/testing/runtime-data-deployment.md",
  "docs/technical/testing/ui-state-and-browser.md"
]);

const VOLATILE_FACT_PATTERNS = [
  {
    name: "pass total",
    pattern:
      /(?:\b(?:pass(?:es|ed)?|green|matching|coverage)\b[^.\n]{0,80}\b\d[\d,]*\s*\/\s*\d[\d,]*\b|\b\d[\d,]*\s*\/\s*\d[\d,]*\b[^.\n]{0,60}\b(?:pass(?:es|ed)?|tests?|cases?|goldens?|comparisons?|paths?)\b)/i
  },
  { name: "artifact hash", pattern: /\b(?:sha-?256|[a-f0-9]{40,64})\b/i },
  {
    name: "module graph count",
    pattern: /\b\d[\d,]*(?:[- /]|\s+)(?:source[- ]modules?|client-reachable|entrypoints?)\b/i
  },
  {
    name: "artifact measurement",
    pattern: /\b\d[\d,.]*\s*(?:raw|gzip|bytes?|kib|mib|kb|mb)\b/i
  },
  { name: "test total", pattern: /\b\d[\d,]*\s+(?:tests?|goldens?|cases?)\b/i }
];

const VOLATILE_FACT_ALLOWLIST: Readonly<Record<string, readonly RegExp[]>> = {
  "docs/operations/README.md": [/D-098-rebased direct entry-JavaScript limits/],
  "docs/technical/testing/accessibility-manual.md": [/\bAT-\d+\b/],
  "docs/technical/testing/ui-state-and-browser.md": [/\bCB-\d+\b/]
};

function diagnostic(
  file: string,
  line: number,
  code: string,
  message: string
): DocumentationDiagnostic {
  return { file, line, code, message };
}

function normalizedFile(file: string): string {
  return file.replaceAll("\\", "/").replace(/^\.\//, "");
}

function withoutFencedCode(text: string): string {
  let fenced = false;
  return text
    .split(/\r?\n/)
    .map((line) => {
      if (/^\s*```/.test(line)) {
        fenced = !fenced;
        return "";
      }
      return fenced ? "" : line;
    })
    .join("\n");
}

function metadataScope(file: string): boolean {
  return (
    file.endsWith("-spec.md") ||
    (/^docs\/project\/goals\/[^/]+\.md$/.test(file) && !file.endsWith("/README.md")) ||
    file === "docs/project/documentation-structure/README.md" ||
    file === "docs/project/testing-evidence.md" ||
    file.startsWith("docs/project/testing-evidence/") ||
    file === "docs/project/audit-evidence.md" ||
    file === "docs/project/generated-evidence.md" ||
    file === "docs/project/backlog-history.md" ||
    file === "docs/project/feature-delivery-history.md" ||
    file === "docs/technical/testing/historical-evidence-2026-07.md" ||
    file === "docs/technical/testing-current-state-history-2026-07.md" ||
    file === "docs/technical/rewrite-parity-report.md" ||
    /^docs\/project\/.*audit\.md$/.test(file) ||
    file === "docs/project/planner-parity/current.md" ||
    file === "docs/project/revision-impact/current.md"
  );
}

function parseMetadataBlock(
  file: string,
  text: string
): { metadata?: DocumentationMetadata; diagnostics: DocumentationDiagnostic[] } {
  const diagnostics: DocumentationDiagnostic[] = [];
  const lines = text.split(/\r?\n/);
  const h1Index = lines.findIndex((line) => /^#\s+\S/.test(line));
  if (h1Index < 0) {
    diagnostics.push(diagnostic(file, 1, "metadata-h1", "metadata owner has no H1"));
    return { diagnostics };
  }

  let index = h1Index + 1;
  while (index < lines.length && lines[index]?.trim() === "") index += 1;
  const values = new Map<string, { value: string; line: number }>();
  let sawCanonicalField = false;

  while (index < lines.length) {
    const line = lines[index] ?? "";
    const fieldMatch = line.match(/^- ([A-Z][A-Za-z ]+):\s*(.*)$/);
    if (!fieldMatch) break;
    const fieldName = fieldMatch[1] ?? "";
    const property = METADATA_FIELDS.get(fieldName as never);
    if (property) {
      sawCanonicalField = true;
      if (values.has(property)) {
        diagnostics.push(
          diagnostic(file, index + 1, "metadata-duplicate", `duplicate ${fieldName} field`)
        );
      } else {
        values.set(property, { value: (fieldMatch[2] ?? "").trim(), line: index + 1 });
      }
    }
    index += 1;
  }

  if (!sawCanonicalField) {
    diagnostics.push(
      diagnostic(file, h1Index + 2, "metadata-position", "canonical metadata must follow the H1")
    );
  }

  for (const field of REQUIRED_METADATA_FIELDS) {
    if (!values.has(field)) {
      diagnostics.push(diagnostic(file, h1Index + 2, "metadata-missing", `missing ${field} field`));
    }
  }

  const statusValue = values.get("status")?.value;
  const dateValue = values.get("date")?.value;
  const ownerValue = values.get("owner")?.value;
  const evidenceValue = values.get("evidence")?.value;
  const contractValue = values.get("contract")?.value;

  if (statusValue && !DOCUMENTATION_STATUSES.includes(statusValue as DocumentationStatus)) {
    diagnostics.push(
      diagnostic(
        file,
        values.get("status")?.line ?? 1,
        "metadata-status",
        `unknown status: ${statusValue}`
      )
    );
  }
  for (const [property, label] of [
    ["date", "Date"],
    ["lastVerified", "Last verified"]
  ] as const) {
    const entry = values.get(property);
    if (entry && !/^\d{4}-\d{2}-\d{2}$/.test(entry.value)) {
      diagnostics.push(
        diagnostic(file, entry.line, "metadata-date", `${label} must use YYYY-MM-DD`)
      );
    }
  }
  if (ownerValue !== undefined && !/[A-Za-zÀ-ÖØ-öø-ÿ]/.test(ownerValue)) {
    diagnostics.push(
      diagnostic(file, values.get("owner")?.line ?? 1, "metadata-owner", "Owner must name an owner")
    );
  }
  if (evidenceValue && !DOCUMENTATION_EVIDENCE.includes(evidenceValue as DocumentationEvidence)) {
    diagnostics.push(
      diagnostic(
        file,
        values.get("evidence")?.line ?? 1,
        "metadata-evidence",
        `unknown evidence state: ${evidenceValue}`
      )
    );
  }
  if (contractValue && !DOCUMENTATION_CONTRACTS.includes(contractValue as DocumentationContract)) {
    diagnostics.push(
      diagnostic(
        file,
        values.get("contract")?.line ?? 1,
        "metadata-contract",
        `unknown contract class: ${contractValue}`
      )
    );
  }
  if (file.startsWith("docs/technical/") && file.endsWith("-spec.md") && !contractValue) {
    diagnostics.push(
      diagnostic(file, h1Index + 2, "metadata-contract", "technical specification needs Contract")
    );
  }
  if (statusValue === "generated" && !values.get("generatedBy")?.value) {
    diagnostics.push(
      diagnostic(
        file,
        values.get("status")?.line ?? 1,
        "metadata-generated",
        "generated status needs Generated by"
      )
    );
  }
  if (statusValue === "superseded" && !values.get("supersededBy")?.value) {
    diagnostics.push(
      diagnostic(
        file,
        values.get("status")?.line ?? 1,
        "metadata-superseded",
        "superseded status needs Superseded by"
      )
    );
  }
  if (statusValue === "implemented" && evidenceValue === "not-run") {
    diagnostics.push(
      diagnostic(
        file,
        values.get("evidence")?.line ?? 1,
        "metadata-evidence",
        "implemented status cannot use not-run evidence"
      )
    );
  }

  if (
    diagnostics.some((entry) =>
      [
        "metadata-missing",
        "metadata-position",
        "metadata-status",
        "metadata-date",
        "metadata-owner",
        "metadata-evidence",
        "metadata-contract"
      ].includes(entry.code)
    ) ||
    !statusValue ||
    !dateValue ||
    !ownerValue
  ) {
    return { diagnostics };
  }

  return {
    diagnostics,
    metadata: {
      status: statusValue as DocumentationStatus,
      date: dateValue,
      owner: ownerValue,
      lastVerified: values.get("lastVerified")?.value,
      evidence: evidenceValue as DocumentationEvidence | undefined,
      parentGoal: values.get("parentGoal")?.value,
      supersededBy: values.get("supersededBy")?.value,
      contract: contractValue as DocumentationContract | undefined,
      generatedBy: values.get("generatedBy")?.value
    }
  };
}

export function parseDocumentationMetadata(
  file: string,
  text: string
): { metadata?: DocumentationMetadata; diagnostics: readonly DocumentationDiagnostic[] } {
  return parseMetadataBlock(normalizedFile(file), text);
}

function markdownSlug(label: string): string {
  return label
    .toLocaleLowerCase("en-US")
    .replace(/<[^>]+>/g, "")
    .replace(/[`*_~]/g, "")
    .replace(/[^\p{L}\p{N}\s_-]/gu, "")
    .trim()
    .replace(/\s+/g, "-");
}

function documentAnchors(text: string): ReadonlySet<string> {
  const anchors = new Set<string>();
  const occurrences = new Map<string, number>();
  for (const line of withoutFencedCode(text).split(/\r?\n/)) {
    const heading = line.match(/^#{1,6}\s+(.+?)\s*#*\s*$/)?.[1];
    if (!heading) continue;
    const base = markdownSlug(heading);
    const count = occurrences.get(base) ?? 0;
    occurrences.set(base, count + 1);
    anchors.add(count === 0 ? base : `${base}-${count}`);
  }
  return anchors;
}

interface LocalLink {
  readonly line: number;
  readonly target: string;
}

function localLinks(text: string): readonly LocalLink[] {
  const links: LocalLink[] = [];
  const source = withoutFencedCode(text);
  for (const [lineIndex, line] of source.split(/\r?\n/).entries()) {
    const pattern = /!?\[[^\]]*\]\(([^)]+)\)/g;
    for (const match of line.matchAll(pattern)) {
      let target = (match[1] ?? "").trim();
      if (target.startsWith("<") && target.endsWith(">")) target = target.slice(1, -1);
      target = target.split(/\s+["']/)[0] ?? target;
      if (target === "" || /^(?:[a-z][a-z\d+.-]*:|\/\/)/i.test(target) || target.startsWith("/")) {
        continue;
      }
      links.push({ line: lineIndex + 1, target });
    }
  }
  return links;
}

function decoded(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

function resolveLink(sourceFile: string, target: string): { file: string; anchor?: string } {
  const [pathPart = "", anchorPart] = target.split("#", 2);
  const file = pathPart
    ? posix.normalize(posix.join(posix.dirname(sourceFile), decoded(pathPart)))
    : sourceFile;
  return { file, anchor: anchorPart ? decoded(anchorPart).toLocaleLowerCase("en-US") : undefined };
}

function documentedNpmCommands(text: string): readonly { line: number; command: string }[] {
  const results: { line: number; command: string }[] = [];
  for (const [lineIndex, line] of text.split(/\r?\n/).entries()) {
    for (const match of line.matchAll(/\bnpm run ([a-zA-Z0-9:_-]+)/g)) {
      results.push({ line: lineIndex + 1, command: match[1] ?? "" });
    }
  }
  return results;
}

function checkVolatileFacts(file: string, text: string): readonly DocumentationDiagnostic[] {
  if (!VOLATILE_FACT_FILES.has(file)) return [];
  const diagnostics: DocumentationDiagnostic[] = [];
  const allowlist = VOLATILE_FACT_ALLOWLIST[file] ?? [];
  for (const [lineIndex, line] of withoutFencedCode(text).split(/\r?\n/).entries()) {
    if (allowlist.some((pattern) => pattern.test(line))) continue;
    for (const rule of VOLATILE_FACT_PATTERNS) {
      if (rule.pattern.test(line)) {
        diagnostics.push(
          diagnostic(
            file,
            lineIndex + 1,
            "volatile-fact",
            `${rule.name} belongs in dated evidence, not this living owner`
          )
        );
        break;
      }
    }
  }
  return diagnostics;
}

function expectedCatalogGroup(metadata: DocumentationMetadata): string {
  if (["draft", "specced", "active"].includes(metadata.status)) return "Active contracts";
  if (metadata.status === "implemented" && metadata.contract === "living") {
    return "Living contracts";
  }
  if (metadata.status === "implemented") return "Implemented evidence";
  return "Superseded or historical";
}

function documentTitle(text: string): string {
  return text.match(/^#\s+(.+?)\s*$/m)?.[1]?.trim() ?? "";
}

export function createSpecificationCatalogPlan(
  files: Readonly<Record<string, string>>,
  metadata: ReadonlyMap<string, DocumentationMetadata>
): readonly SpecificationCatalogPlanEntry[] {
  return Object.keys(files)
    .filter((file) => file.startsWith("docs/technical/") && file.endsWith("-spec.md"))
    .flatMap((file) => {
      const documentMetadata = metadata.get(file);
      const contract = documentMetadata?.contract;
      if (!documentMetadata || !contract) return [];
      const label = documentTitle(files[file] ?? "");
      return [
        {
          file,
          group: expectedCatalogGroup(documentMetadata),
          label,
          status: documentMetadata.status,
          contract,
          owner: documentMetadata.owner,
          date: documentMetadata.date,
          line:
            `- [${label}](${posix.basename(file)}) — ` +
            `status=\`${documentMetadata.status}\`; contract=\`${contract}\`; ` +
            `owner=${documentMetadata.owner}; date=${documentMetadata.date}`
        }
      ];
    })
    .sort(
      (left, right) =>
        left.group.localeCompare(right.group, "en") || left.label.localeCompare(right.label, "en")
    );
}

function checkSpecificationCatalog(
  files: Readonly<Record<string, string>>,
  metadata: ReadonlyMap<string, DocumentationMetadata>
): readonly DocumentationDiagnostic[] {
  const catalogFile = "docs/technical/specifications.md";
  const catalog = files[catalogFile];
  if (catalog === undefined) {
    return [
      diagnostic(catalogFile, 1, "catalog-missing", "technical specification catalog is missing")
    ];
  }
  const diagnostics: DocumentationDiagnostic[] = [];
  const entries = new Map<
    string,
    {
      group: string;
      line: number;
      label?: string;
      status?: string;
      contract?: string;
      owner?: string;
      date?: string;
    }[]
  >();
  let group = "";
  for (const [lineIndex, line] of catalog.split(/\r?\n/).entries()) {
    const heading = line.match(/^##\s+(.+)$/)?.[1];
    if (heading) group = heading.trim();
    const link = line.match(/^- \[([^\]]+)\]\(([^)#]+-spec\.md)\)/);
    if (!link) continue;
    const target = resolveLink(catalogFile, link[2] ?? "").file;
    const status = line.match(/status=`([^`]+)`/)?.[1];
    const contract = line.match(/contract=`([^`]+)`/)?.[1];
    const owner = line.match(/; owner=(.*); date=/)?.[1];
    const date = line.match(/; date=(\d{4}-\d{2}-\d{2})$/)?.[1];
    const existing = entries.get(target) ?? [];
    existing.push({
      group,
      line: lineIndex + 1,
      label: link[1],
      status,
      contract,
      owner,
      date
    });
    entries.set(target, existing);
  }

  const plan = createSpecificationCatalogPlan(files, metadata);
  const planByFile = new Map(plan.map((entry) => [entry.file, entry]));
  const specifications = plan.map((entry) => entry.file);
  for (const file of specifications) {
    const rows = entries.get(file) ?? [];
    if (rows.length === 0) {
      diagnostics.push(
        diagnostic(catalogFile, 1, "catalog-unclassified", `${file} is not classified`)
      );
      continue;
    }
    if (rows.length > 1) {
      diagnostics.push(
        diagnostic(
          catalogFile,
          rows[1]?.line ?? 1,
          "catalog-duplicate",
          `${file} appears more than once`
        )
      );
      continue;
    }
    const expected = planByFile.get(file);
    if (!expected) continue;
    const row = rows[0];
    if (row?.group !== expected.group) {
      diagnostics.push(
        diagnostic(
          catalogFile,
          row?.line ?? 1,
          "catalog-group",
          `${file} belongs in ${expected.group}, not ${row?.group || "an unnamed group"}`
        )
      );
    }
    if (
      row?.label !== expected.label ||
      row?.status !== expected.status ||
      row.contract !== expected.contract ||
      row.owner !== expected.owner ||
      row.date !== expected.date
    ) {
      diagnostics.push(
        diagnostic(
          catalogFile,
          row?.line ?? 1,
          "catalog-metadata",
          `${file} catalog row disagrees with the deterministic metadata plan`
        )
      );
    }
  }
  for (const [file, rows] of entries) {
    if (!specifications.includes(file)) {
      diagnostics.push(
        diagnostic(
          catalogFile,
          rows[0]?.line ?? 1,
          "catalog-target",
          `${file} is not a technical specification`
        )
      );
    }
  }
  return diagnostics;
}

export function checkDocumentation(input: DocumentationCheckInput): DocumentationCheckResult {
  const files = Object.fromEntries(
    Object.entries(input.files).map(([file, text]) => [normalizedFile(file), text])
  );
  const rootDocument = input.rootDocument ?? "docs/README.md";
  const diagnostics: DocumentationDiagnostic[] = [];
  const metadata = new Map<string, DocumentationMetadata>();
  const graph = new Map<string, Set<string>>();
  const anchorCache = new Map<string, ReadonlySet<string>>();

  for (const [file, text] of Object.entries(files)) {
    graph.set(file, new Set());
    if (metadataScope(file)) {
      const parsed = parseMetadataBlock(file, text);
      diagnostics.push(...parsed.diagnostics);
      if (parsed.metadata) metadata.set(file, parsed.metadata);
    }
    diagnostics.push(...checkVolatileFacts(file, text));

    for (const command of documentedNpmCommands(text)) {
      if (!input.packageScripts.has(command.command)) {
        diagnostics.push(
          diagnostic(
            file,
            command.line,
            "npm-command",
            `npm script does not exist: ${command.command}`
          )
        );
      }
    }
    for (const link of localLinks(text)) {
      const resolved = resolveLink(file, link.target);
      if (!resolved.file.endsWith(".md")) continue;
      const targetText = files[resolved.file];
      if (targetText === undefined) {
        diagnostics.push(
          diagnostic(
            file,
            link.line,
            "link-file",
            `Markdown target does not exist: ${resolved.file}`
          )
        );
        continue;
      }
      graph.get(file)?.add(resolved.file);
      if (resolved.anchor) {
        const anchors = anchorCache.get(resolved.file) ?? documentAnchors(targetText);
        anchorCache.set(resolved.file, anchors);
        if (!anchors.has(resolved.anchor)) {
          diagnostics.push(
            diagnostic(
              file,
              link.line,
              "link-anchor",
              `heading anchor does not exist: ${resolved.file}#${resolved.anchor}`
            )
          );
        }
      }
    }
  }

  const reachability = new Map<string, number>();
  const queue: { file: string; depth: number }[] = [{ file: rootDocument, depth: 0 }];
  while (queue.length > 0) {
    const current = queue.shift();
    if (!current || reachability.has(current.file) || files[current.file] === undefined) continue;
    reachability.set(current.file, current.depth);
    for (const target of graph.get(current.file) ?? []) {
      if (!reachability.has(target)) queue.push({ file: target, depth: current.depth + 1 });
    }
  }
  for (const file of Object.keys(files).filter((entry) => entry.startsWith("docs/"))) {
    const depth = reachability.get(file);
    if (depth === undefined) {
      diagnostics.push(
        diagnostic(file, 1, "navigation-unreachable", `not reachable from ${rootDocument}`)
      );
      continue;
    }
    const generated = metadata.get(file)?.status === "generated";
    const limit = generated ? 3 : 2;
    if (depth > limit) {
      diagnostics.push(
        diagnostic(file, 1, "navigation-depth", `reachable at depth ${depth}; maximum is ${limit}`)
      );
    }
  }

  diagnostics.push(...checkSpecificationCatalog(files, metadata));
  diagnostics.sort(
    (left, right) =>
      left.file.localeCompare(right.file) ||
      left.line - right.line ||
      left.code.localeCompare(right.code)
  );
  return { diagnostics, metadata, reachability };
}
